---
title: "Untitled"
author: "Katherine Rosencrance"
date: "11/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(beepr)
library(praise)
library(cowsay)
library(paletteer)
library(sf)
library(tidyverse)
library(usethis)
library(janitor)

```

# beepr beeps

use the function 'beep()' to make audio alert when your code is done running

```{r, eval = FALSE}
for (i in rev(seq(1:99))) {
  
  print(paste(i, "bottles of beer on the wall"))
}

 # beep(4)
```

## Praise and cowsay

Packages built with a single purpose: to be kind and fun

```{r}
praise("${Exclamation}, ${EXCLAMATION}...${exclamation}!!!!")

```

Use cowsay say() to make a chracter say something to you

## use paletteer to access thousands of color pallettes

```{r}
storms %>% 
  group_by(name) %>% 
  summarize(min_pressure = min(pressure, na.rm = TRUE)) %>% 
  slice_min(n= 10, min_pressure) %>% 
  ggplot(aes( x = min_pressure, y = name))+
  geom_col(aes(fill = name))+
  scale_fill_paletteer_d("palettetown::roselia")
```


